import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import './App.css';

function About() {
  useEffect(() => {
    document.title = 'About SiPPP';
  }, []);

  return (
    <div id="sippp">
        <div className="container content">
        <Link to="/">
            <img src="https://www.sippp.box/sippp-logo-transparent.png" className="about-logo" alt="logo" />
        </Link>
        <h1>SiPPP: the Simple Photo Provenance Protocol</h1>

        <h2>What</h2>
        <p>SiPPP, the Simple Photo Provenance Protocol, is a straightforward method 
            for registering unaltered camera photos on the Base blockchain via a mobile app.
            This protocol ensures that anyone viewing the photo can verify its authenticity, 
            confirming it was taken with a camera and not altered or generated by AI.
            Additionally, SiPPP verifies who took the photo and when it was taken, 
            providing an extra layer of credibility.
        </p>
 
        <h2>Why</h2>
        <p>AI is dominating the headlines, it's hard to tell if photos are real, enhanced, 
            misinformation, bullying, or just something we've never seen before, 
            and many people are harmed as a result. As we scroll through 
            socials or watch the news, there's no simple, accessible way to verify 
            photo provenance, 
            which affects our confidence and our decision making. Impressionable minds 
            will believe absurdity on socials and harm themselves striving to achieve 
            a false standard; Misinformation will subtley work its way as people can't 
            easily differentiate; Real information may be dismissed and rob someone of 
            justice; Unrealistic beauty standards may lead to depression or worse. 
            We need an "at a glance" solution to verify a photo hasn't been altered, 
            to verifying photo provenance.
        </p>

        <h2>How</h2>
        <p>tktktk</p>
        </div>
    </div>
  );
}

export default About;
